TOKEN: 6373586120:AAEZbSBVAsv_fZIT97kMMR3qldI9yFk73w0
mysql_ip: localhost
mysql_port: 3306
mysql_user: TestUser
mysql_password: testpass
mysql_general_database: Bot
# Change to your MySQL Data and bot token